public enum LANGUAGE_TYPE
{
     LANGUAGE_TYPE_KOR = 0,
}
public enum ACTOR_TYPE
{
     ACTOR_TYPE_PLAYER = 0,
     ACTOR_TYPE_MONSTER = 1,
}
public enum MONSTER_TYPE
{
     MONSTER_TYPE_WARRIOR = 0,
     MONSTER_TYPE_SHAMAN = 1,
     MONSTER_TYPE_TANKER = 2,
}
public enum PHASE_CONDITION
{
     PHASE_CONDITION_NONE = 0,
     PHASE_CONDITION_HP_CONDITION = 1,
}
public enum PATTERN_TYPE
{
     PATTERN_TYPE_RANDOM = 0,
     PATTERN_TYPE_SEQUENTIAL = 1,
}
public enum SKIP_CONDITION
{
     SKIP_CONDITION_NONE = 0,
     SKIP_CONDITION_HP_CONDITION = 1,
}
public enum EFFECT_TAG
{
     EFFECT_TAG_DAMAGE = 0,
     EFFECT_TAG_HEAL = 1,
     EFFECT_TAG_DRAW = 2,
     EFFECT_TAG_ARMOR = 3,
     EFFECT_TAG_BUFF = 4,
     EFFECT_TAG_DEBUFF = 5,
}
public enum EFFECT_TYPE
{
     EFFECT_TYPE_DAMAGE = 0,
     EFFECT_TYPE_HEAL = 1,
     EFFECT_TYPE_DOT_SKILL_DAMAGE = 2,
     EFFECT_TYPE_DOT_HEAL = 3,
     EFFECT_TYPE_DRAW = 4,
     EFFECT_TYPE_ARMOR = 5,
     EFFECT_TYPE_ARMOR_DOWN = 6,
     EFFECT_TYPE_DEBUFF_DISPEL = 7,
     EFFECT_TYPE_BUFF_DISPEL = 8,
     EFFECT_TYPE_AP_UP = 9,
     EFFECT_TYPE_AP_STOP = 10,
     EFFECT_TYPE_ACTION_CANCEL = 11,
     EFFECT_TYPE_FUSION_LEVEL_UP = 12,
     EFFECT_TYPE_STUN = 13,
     EFFECT_TYPE_REFLECT_DAMAGE = 14,
     EFFECT_TYPE_REFLECT_DAMAGE_PER = 15,
     EFFECT_TYPE_DAMAGE_INVINCIBLE = 16,
     EFFECT_TYPE_AVOID_UP = 17,
     EFFECT_TYPE_AVOID_DOWN = 18,
     EFFECT_TYPE_ALL_UP_PER = 19,
     EFFECT_TYPE_ALL_DOWN_PER = 20,
     EFFECT_TYPE_DOT_DRAW = 21,
     EFFECT_TYPE_DEBUFF_ACCURACY_UP = 22,
     EFFECT_TYPE_DEBUFF_ACCURACY_DOWN = 23,
     EFFECT_TYPE_DEBUFF_RESISTANCE_UP = 24,
     EFFECT_TYPE_DEBUFF_RESISTANCE_DOWN = 25,
     EFFECT_TYPE_DAMAGE_SPREAD = 26,
     EFFECT_TYPE_PROVOKE = 27,
     EFFECT_TYPE_COUNTER = 28,
}
public enum SUPPORT_MODULE_EFFECT
{
     SUPPORT_MODULE_EFFECT_REDUCE_PRODUCT_AP = 0,
     SUPPORT_MODULE_EFFECT_INCREASE_PRODUCT_AP = 1,
     SUPPORT_MODULE_EFFECT_REDUCE_PRODUCT_VALUE = 2,
     SUPPORT_MODULE_EFFECT_INCREASE_PRODUCT_VALUE = 3,
     SUPPORT_MODULE_EFFECT_CHANGE_PRODUCT_SPELL = 4,
}
public enum TARGET_TYPE
{
     TARGET_TYPE_SELF = 0,
     TARGET_TYPE_ENEMY = 1,
     TARGET_TYPE_ALLY_HP_HIGHEST = 2,
     TARGET_TYPE_ALLY_HP_LOWEST = 3,
}
public enum MAP_TYPE
{
     MAP_TYPE_BATTLE_NORMAL = 0,
     MAP_TYPE_BATTLE_ELITE = 1,
     MAP_TYPE_BATTLE_BOSS = 2,
     MAP_TYPE_SHOP = 3,
     MAP_TYPE_ENHANCE = 4,
}
