public enum LANGUAGE_TYPE
{
     LANGUAGE_TYPE_KOR = 0,
}
public enum ACTOR_TYPE
{
     ACTOR_TYPE_PLAYER = 0,
     ACTOR_TYPE_MONSTER = 1,
}
public enum EFFECT_TYPE
{
     EFFECT_TYPE_DAMAGE = 0,
     EFFECT_TYPE_HEAL = 1,
     EFFECT_TYPE_DOT_SKILL_DAMAGE = 2,
     EFFECT_TYPE_DOT_HEAL = 3,
     EFFECT_TYPE_DRAW = 4,
     EFFECT_TYPE_ARMOR = 5,
     EFFECT_TYPE_ARMOR_DOWN = 6,
     EFFECT_TYPE_DEBUFF_DISPEL = 7,
     EFFECT_TYPE_BUFF_DISPEL = 8,
     EFFECT_TYPE_AP_UP = 9,
     EFFECT_TYPE_AP_STOP = 10,
     EFFECT_TYPE_ACTION_CANCEL = 11,
     EFFECT_TYPE_FUSION_LEVEL_UP = 12,
     EFFECT_TYPE_STUN = 13,
     EFFECT_TYPE_REFLECT_DAMAGE = 14,
     EFFECT_TYPE_REFLECT_DAMAGE_PER = 15,
     EFFECT_TYPE_DAMAGE_INVINCIBLE = 16,
     EFFECT_TYPE_AVOID_UP = 17,
     EFFECT_TYPE_AVOID_DOWN = 18,
     EFFECT_TYPE_ALL_UP_PER = 19,
     EFFECT_TYPE_ALL_DOWN_PER = 20,
     EFFECT_TYPE_DOT_DRAW = 21,
     EFFECT_TYPE_DEBUFF_ACCURACY_UP = 22,
     EFFECT_TYPE_DEBUFF_ACCURACY_DOWN = 23,
     EFFECT_TYPE_DEBUFF_RESISTANCE_UP = 24,
     EFFECT_TYPE_DEBUFF_RESISTANCE_DOWN = 25,
     EFFECT_TYPE_DAMAGE_SPREAD = 26,
     EFFECT_TYPE_PROVOKE = 27,
     EFFECT_TYPE_COUNTER = 28,
}
public enum TARGET_TYPE
{
     TARGET_TYPE_ALLY = 0,
     TARGET_TYPE_ENEMY = 1,
}
