public enum LANGUAGE_TYPE
{
     LANGUAGE_TYPE_KOR = 0,
}
public enum ACTOR_TYPE
{
     ACTOR_TYPE_PLAYER = 0,
     ACTOR_TYPE_MONSTER = 1,
     ACTOR_TYPE_NPC = 2,
}
public enum MONSTER_TYPE
{
     MONSTER_TYPE_WARRIOR = 0,
     MONSTER_TYPE_SHAMAN = 1,
     MONSTER_TYPE_TANKER = 2,
}
public enum PHASE_CONDITION
{
     PHASE_CONDITION_NONE = 0,
     PHASE_CONDITION_HP_CONDITION = 1,
}
public enum PATTERN_TYPE
{
     PATTERN_TYPE_RANDOM = 0,
     PATTERN_TYPE_SEQUENTIAL = 1,
}
public enum SKIP_CONDITION
{
     SKIP_CONDITION_NONE = 0,
     SKIP_CONDITION_HP_CONDITION = 1,
}
public enum EFFECT_TAG
{
     EFFECT_TAG_DAMAGE = 0,
     EFFECT_TAG_HEAL = 1,
     EFFECT_TAG_DRAW = 2,
     EFFECT_TAG_ARMOR = 3,
     EFFECT_TAG_BUFF = 4,
     EFFECT_TAG_DEBUFF = 5,
}
public enum EFFECT_TYPE
{
     EFFECT_TYPE_DAMAGE = 0,
     EFFECT_TYPE_HEAL = 1,
     EFFECT_TYPE_DOT_SKILL_DAMAGE = 2,
     EFFECT_TYPE_DOT_HEAL = 3,
     EFFECT_TYPE_DRAW = 4,
     EFFECT_TYPE_ARMOR = 5,
     EFFECT_TYPE_ARMOR_DOWN = 6,
     EFFECT_TYPE_DEBUFF_DISPEL = 7,
     EFFECT_TYPE_BUFF_DISPEL = 8,
     EFFECT_TYPE_AP_UP = 9,
     EFFECT_TYPE_AP_STOP = 10,
     EFFECT_TYPE_ACTION_CANCEL = 11,
     EFFECT_TYPE_FUSION_LEVEL_UP = 12,
     EFFECT_TYPE_STUN = 13,
     EFFECT_TYPE_DAMAGE_INVINCIBLE = 14,
     EFFECT_TYPE_ALL_UP_PER = 15,
     EFFECT_TYPE_ALL_DOWN_PER = 16,
     EFFECT_TYPE_DOT_DRAW = 17,
     EFFECT_TYPE_PROVOKE = 18,
     EFFECT_TYPE_COUNTER = 19,
     EFFECT_TYPE_DOT_AMOR = 20,
     EFFECT_TYPE_TAKE_DAMAGE_UP_BUFF = 21,
     EFFECT_TYPE_TAKE_DAMAGE_DOWN_BUFF = 22,
     EFFECT_TYPE_GIVE_DAMAGE_UP_BUFF = 23,
     EFFECT_TYPE_GIVE_DAMAGE_DOWN_BUFF = 24,
     EFFECT_TYPE_INVALID_DAMAGE = 25,
     EFFECT_TYPE_IGNORE_DAMAGE = 26,
     EFFECT_TYPE_HEAL_PROPORTION_GIVEN_DAMAGE = 27,
     EFFECT_TYPE_HEAL_PROPORTION_TAKEN_DAMAGE = 28,
     EFFECT_TYPE_DAMAGE_PROPORTION_OVERHEAL = 29,
     EFFECT_TYPE_GIVE_DAMAGE_UP_FIXED = 30,
     EFFECT_TYPE_GIVE_DAMAGE_DOWN_FIXED = 31,
     EFFECT_TYPE_GIVE_TRUE_DAMAGE_UP = 32,
}
public enum SUPPORT_MODULE_EFFECT
{
     SUPPORT_MODULE_EFFECT_REDUCE_PRODUCT_AP = 0,
     SUPPORT_MODULE_EFFECT_INCREASE_PRODUCT_AP = 1,
     SUPPORT_MODULE_EFFECT_REDUCE_PRODUCT_VALUE = 2,
     SUPPORT_MODULE_EFFECT_INCREASE_PRODUCT_VALUE = 3,
     SUPPORT_MODULE_EFFECT_CHANGE_PRODUCT_SPELL = 4,
}
public enum TARGET_TYPE
{
     TARGET_TYPE_SELF = 0,
     TARGET_TYPE_ENEMY = 1,
     TARGET_TYPE_ALLY_HP_HIGHEST = 2,
     TARGET_TYPE_ALLY_HP_LOWEST = 3,
     TARGET_TYPE_ENEMY_ALL = 4,
     TARGET_TYPE_ALLY_ALL = 5,
}
public enum ACTIVE_CONDITION
{
     ACTIVE_CONDITION_BATTLE_START = 0,
     ACTIVE_CONDITION_BATTLE_END = 1,
     ACTIVE_CONDITION_HP_MINUS_VALUE = 2,
     ACTIVE_CONDITION_HP_PERCENT = 3,
}
public enum RELIC_EFFECT
{
     RELIC_EFFECT_HEAL = 0,
     RELIC_EFFECT_ARMOR = 1,
}
public enum MAP_TYPE
{
     MAP_TYPE_BATTLE_NORMAL = 0,
     MAP_TYPE_BATTLE_ELITE = 1,
     MAP_TYPE_BATTLE_BOSS = 2,
     MAP_TYPE_SHOP = 3,
     MAP_TYPE_ENHANCE = 4,
     MAP_TYPE_SPECIAL = 5,
}
public enum REWARD_TYPE
{
     REWARD_TYPE_ITEM = 0,
     REWARD_TYPE_SPELL_SOURCE = 1,
     REWARD_TYPE_SUPPORT_MODULE = 2,
     REWARD_TYPE_MONEY = 3,
}
public enum EXCEPTION_TYPE
{
     EXCEPTION_TYPE_OWN_SPELL_SOURCE = 0,
     EXCEPTION_TYPE_NO_SPELL_SOURCE = 1,
     EXCEPTION_TYPE_CLEAR_MAP = 2,
     EXCEPTION_TYPE_NOT_CLEAR_MAP = 3,
}
public enum RARITY
{
     RARITY_NORMAL = 0,
     RARITY_RARE = 1,
     RARITY_EPIC = 2,
}
public enum LOGICAL_OPERATOR
{
     LOGICAL_OPERATOR_AND = 0,
     LOGICAL_OPERATOR_OR = 1,
}
public enum DIALOG_TYPE
{
     DIALOG_TYPE_TITLE = 0,
     DIALOG_TYPE_TEXT = 1,
     DIALOG_TYPE_BUTTON = 2,
}
public enum BUTTON_FUNCTION
{
     BUTTON_FUNCTION_REWARD = 0,
     BUTTON_FUNCTION_SELECT_REWARD = 1,
     BUTTON_FUNCTION_DELETE_SOURCE = 2,
     BUTTON_FUNCTION_DELETE_SUPPORT_MODULE = 3,
     BUTTON_FUNCTION_DELETE_RELIC = 4,
     BUTTON_FUNCTION_SHOP = 5,
     BUTTON_FUNCTION_ENHANCE = 6,
     BUTTON_FUNCTION_EXCHANGE = 7,
     BUTTON_FUNCTION_EXIT = 8,
}
public enum ITEM_TYPE
{
     ITEM_TYPE_SOURCE = 0,
     ITEM_TYPE_SUPPORT_MODULE = 1,
     ITEM_TYPE_RELIC = 2,
}
